"""Documented host boundaries, not a fake implementation of AionsHome.

The deployment agent implements these against its existing runtime. Never
mount the MIRROW reference admin routers on the public listener.
"""
from typing import Protocol, Any


class VisitorCredentialPort(Protocol):
    def authenticate_identity(self, raw_key: str) -> tuple[str,str] | None: ...
    def authenticate_bearer_identity(self, raw_key: str) -> tuple[str,str] | None: ...
    def credential_active(self, key_id: str, visitor_id: str) -> bool: ...
    def effective_visitor(self, visitor_id: str) -> Any: ...


class LoungeImportPort(Protocol):
    def inbound_candidates(self) -> list[dict]:
        """Stable id/kind/status/display_name/key presence only, never raw Keys."""
        ...
    def outbound_ai_candidates(self) -> list[dict]: ...
    def import_outbound_ai_key(self, friend_id: str, local_ai_id: str) -> str:
        """Server-only secret. Same AI must own this lounge friend reference."""
        ...


class CognitionPort(Protocol):
    def candidates(self, identity_name: str) -> list[dict]: ...
    def resolve(self, stable_connection_id: str) -> dict | None: ...
    def confirm_binding(self, stable_connection_id: str, entity_id: str) -> dict: ...
    def create_and_confirm(self, stable_connection_id: str, identity_name: str) -> dict: ...


class ActivityPort(Protocol):
    async def build_activity_context(self, local_ai_id: str, site_id: str, invite_reason: str, prior_receipts: list[dict]) -> list[dict]: ...
    async def generate(self, local_ai_id: str, messages: list[dict], contract: dict) -> dict: ...
    async def publish_event(self, local_ai_id: str, real_receipts: list[dict], feeling: str, source: str) -> dict: ...


class OptionalHomePorts(Protocol):
    def music_choices(self) -> list[dict]:
        """Optional cached metadata only. No available library => empty list."""
        ...
    async def draft_exhibit(self, local_ai_id: str, draft: dict) -> dict:
        """Uses this family's real persona/context, never an empty replacement model."""
        ...
